// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {upload} from '../models';

export function LoadConfig():Promise<string>;

export function Preview(arg1:string):Promise<string>;

export function SaveConfig(arg1:string):Promise<string>;

export function SelectFile():Promise<string>;

export function UploadFile(arg1:string,arg2:upload.BedType):Promise<string>;
